import type { Metadata } from "next";
import {Work_Sans, Libre_Baskerville} from "next/font/google"
import "./globals.scss";

const geistSans = Work_Sans({subsets: ["latin"],
  variable: "--font-geist-sans",
  weight: ["100", "400", "900"],
});
const geistMono = Libre_Baskerville({subsets: ["latin"],

  variable: "--font-geist-mono",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased default-grid`}
      >
        {children}
      </body>
    </html>
  );
}
